import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50,
            info: {
                Author: "M.AI",
                Title: data.title,
                Creator: "M.AI"
            }
        });

        const chunks = [];

        doc.on("data", (chunk) => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        
        // FIX: Properly pass the error to reject
        doc.on("error", reject); 

        // Title
        doc
            .fontSize(28)
            .fillColor("#111827") // FIX: Set color BEFORE drawing text
            .text(data.title, {
                align: "center"
            });

        if (data.subtitle) {
            doc.moveDown(0.5);
            
            // Subtitle
            doc
                .fontSize(12)
                .fillColor("#6B7280") // FIX: Set color BEFORE drawing text
                .text(data.subtitle, {
                    align: "center"
                });
        }

        doc.moveDown(2);

        // Sections
        data?.sections?.forEach((s) => {
            doc
                .fontSize(18)
                .fillColor("#111827") // FIX: Set color BEFORE drawing text
                .text(s.heading);

            doc.moveDown(0.5);

            s?.points?.forEach((p) => {
                doc
                    .fontSize(12) // FIX: Made points smaller than the heading
                    .fillColor("#374151") // FIX: Set color BEFORE drawing text
                    .text("- " + p, { // FIX: Replaced '●' with standard hyphen '-'
                        lineGap: 5
                    });
            });
            
            // Add a little extra space between sections
            doc.moveDown(1.5); 
        });

        // Footer
        doc.moveDown(2);

        doc
            .fontSize(10)
            .fillColor("#9CA3AF") // FIX: Set color BEFORE drawing text
            .text("Generated By M.AI", {
                align: "center"
            });

        doc.end();
    });
};